Fix kzalloc_flex compatibility for kernel 6.12
kzalloc_flex() was introduced in kernel 6.13+ for flexible array
member allocation. On Raspberry Pi kernel 6.12.62, this function
doesn't exist, causing:

  error: implicit declaration of function 'kzalloc_flex'

Replace with the equivalent kzalloc(struct_size(...), GFP_KERNEL)
which works on all kernel versions.